experiment_name: "walk_vs_run_anomaly"
data:
  normal_activity: "walk"
  anomaly_activity: "run"
  sequence_length: 100
  overlap: 0.5
  feature_type: "joint_angles"

model:
  type: "tcae"
  input_dim: 20
  hidden_dims: [64, 32, 16]
  kernel_size: 3
  dilation_base: 2

training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 100
  early_stopping: true
  patience: 10

evaluation:
  metrics: ["roc_auc", "average_precision", "f1_score"]
  threshold_method: "percentile_95"
